- name: Deploy Flask App
  hosts: server
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - libpq-dev
          - python3-dev
        state: present

    - name: Install Flask
      pip:
        name: flask
        state: present

    - name: Copy application code
      copy:
        src: /path/to/app.py
        dest: /opt/flask_app/app.py
        mode: 0755

    - name: Start application
      command: python3 /opt/flask_app/app.py &
      args:
        creates: /var/run/flask_app.pid

    - name: Configure nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/flask_app
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
