---
- name: Deploy Flask app
  hosts: g
  remote_user: root

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install necessary packages
      apt:
        name:
          - python3-pip
          - python3-dev
          - build-essential
          - python3-venv
          - git
        state: present
      become: yes

    - name: Create virtual environment
      command: python3 -m venv /opt/myapp1/env
      become: yes

    - name: Activate virtual environment
      command: /bin/bash -c "source /opt/myapp1/env/bin/activate"
      become: yes

    #- name: Delete app directory if it exists
    #  become: yes
    #  file:
    #    path: /opt/myapp1
    #    state: absent

    - name: Clone Git repository
      git:
        repo: https://github.com/Opas95/Flask-web-App.git
        dest: /opt/myapp1
        clone: no
      become: yes

    #- name: Install dependencies using requirements.txt
    #  pip:
    #    requirements: /opt/myapp1/requirements.txt
    #    executable: /opt/myapp1/env/bin/pip

    - name: Update myapp1.service file
      copy:
        src: app.py
        dest: /opt/myapp1
      become: yes

    - name: Install flask using pip
      #var: ansible_command
      pip:
        name: flask
        executable: /opt/myapp1/env/bin/pip
        #state: present
      become: yes

    - name: Allow incoming traffic on port 5000
      ufw:
        rule: allow
        proto: tcp
        port: 5000
        comment: "Allow incoming traffic to Flask app"
      become: yes

    - name: Restart UFW
      systemd:
        name: ufw
        state: restarted
      become: yes

    - name: Start Flask app
      become: true
      command: /bin/bash -c "source /opt/myapp1/env/bin/activate && export FLASK_APP=/opt/myapp1/app.py && /opt/myapp1/env/bin/flask run --host=0.0.0.0 &"
      async: 0
      poll: 0

