---
- name: Deploy Flask application
  hosts: g1
  become: yes
  vars:
      project_path: /home/ubuntu/Flaskapp
      venv_path: /home/ubuntu/Flaskapp

  tasks:
    - name: Install required packages
      apt:
        name: python3
        state: present

    - name: Install required packages
      apt:
        name: git
        state: present

    - name: Install required packages
      apt:
        name: pip*
        state: present
          
          #    - name: Package prerequisites for pymongo ansible module
          #      apt:
          #        force_apt_get: yes
          #        name: ['python-pip']
          #        install_recommends: yes
          #        state: present
          #      become: true
    - name: Install required packages
      pip:
        name: gunicorn
        state: present

    - name: Install gunicorn using the 'pip' executable
      ansible.builtin.pip:
        name: gunicorn
        executable: pip
         
    - name: Create Directory
      file:
        path: /home/ubuntu/Flaskapp
        state: directory

    - name: Go to the folder
      command: chdir=/home/ubuntu/Flaskapp ls
 
        #    - name: Install project requirements in venv
        #      pip:
        #        venv: '{{venv_path}}'
        #        venv_python: python3
        
    - name: Install Flask using the 'pip' executable
      ansible.builtin.pip:
        name: Flask
        executable: pip


    - name: Install required packages
      pip:
        name: gunicorn
        state: present

    - name: Update Dynamic Page
      template:
        src: app.py
        dest: '{{project_path}}/app.py'

          #    - name: Run gunicorn on a venv
          #      community.general.gunicorn:
          #        app: 'app'
          #        chdir: /home/ubuntu/Flaskapp/
          #        venv: venv

    - name: Update Flaskapp.service file
      template:
        src: Flaskapp.service
        dest: /etc/systemd/system/Flaskapp.service

    - name: Just force systemd to reread configs (2.4 and above)
      ansible.builtin.systemd:
        daemon_reload: true 

          #    - name: Start service Flaskapp
          #      ansible.builtin.systemd:
          #        name: Flaskapp
          #        state: started 

          #    - name: Enable Flaskapp.service and ensure it is not masked
          #      ansible.builtin.systemd:
          #        name: Flaskapp
          #        enabled: true
          #        masked: no

    - name: Install nginx
      apt:
        name: nginx
        state: present 

    - name: Start nginx 
      ansible.builtin.systemd:
        name: nginx
        state: restarted 

    - name: Enable nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: true  

    - name: Update default file
      template:
        src: default
        dest: /etc/nginx/sites-available/default 
                            
    - name: Start nginx 
      ansible.builtin.systemd:
        name: nginx
        state: restarted                             
...


    


